### ISSUE TITLE
P2P LiveStreaming

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#18]
Get an A/V company to run the livestream, to do participant interviews, and to produce promo materials (especially for IPFS Conf) from that A/V content.

**Comment by VictorBjelkholm** [comment]
Probably one of @yondonfu, @ericxtang or @dob (livepeer team) can answer that better than me.

**Comment by VictorBjelkholm** [comment]
@ericxtang how many clients have you had all together so far? AFAIK, livepeer is setup to have a libp2p stream between each client <> broadcaster, which seems to not scale great, compared to pubsub instead of individual streams.

**Comment by ericxtang** [comment]
@VictorBjelkholm yeah you are right - the current approach with libp2p stream between client / broadcaster doesn't scale.  We fallback to a CDN to ensure playback experience is good.  Would love to try pubsub.  Is there an example anywhere?

**Comment by mgoelzer** [comment]
Update:  Lorenzo will propose a vendor for recording.

Requirement:  LivePeer is great, but if LP gets overloaded with clients, need some live stream that is still accessible in real time.

Ideas:  State of Our Networks is facing the same problem (how to live stream over IPFS) so we should watch how they plan to handle.

**Comment by benhylau** [comment]
We are just planning for State of Our Networks. The plan is to publish ts chunks and m3u8 at multiple ipfs nodes and since most people would be watching through http gateways, we will request those chunks on major gateways to warm the cache. We also will run gateways since public gateways are not very predictable in our experience. See https://github.com/tomeshnet/ipfs-live-streaming/issues/2

We are currently blocked by ipns publishing and retrieval time being too long. If someone from ipfs can comment of this it'd be great help:
https://github.com/tomeshnet/ipfs-live-streaming/issues/3

**Comment by diasdavid** [comment]
This issue has many tasks mixed up. We need:

- A team to handle A/V as in: Projection, Sound
- A team to handle Recording and Live Streaming
- A team to record interviews (can be the same as the recording and interviewing)
- DRI to prepare the interviews, who gets interviewed and what format.
- Bonus: Make it work with LivePeer.

Let's continue using this issue to explore the use of LivePeer (it would be great to have a demo on how to set it up so that we can send to the team that will handle Recording and Live Streaming).

**Comment by mgoelzer** [comment]
@diasdavid I wanted to self-assign this issue (since I am working on a requirements doc for the A/V vendor(s)), but I don't have permissions for this repo.  If it makes sense for me to do these tasks together, either assign to me or give me repo permissions?

**Comment by meiqimichelle** [comment]
@LorenzoPilia is going to look into this.

**Comment by meiqimichelle** [comment]
This is being tracked now with the other A/V stuff in [this issue](https://github.com/protocol/2018-dev-meetings-berlin/issues/12). Closing.
