### ISSUE TITLE
IPFS Website Tech stack

### ISSUE THREAD

**Issue by luisptorres** [ipfs/conf#25]
Hi Everyone.

Regarding the website tech stack, we will be using **Gatsby**, a library that uses **React** to develop and build static websites, with great performance benefits over regular websites. Both are fully open-source.

Besides these libraries we will have **PostCSS**, configured with **precss** and **autoprefixer**, the first adds **SASS**-like markup to regular CSS and the second prefixes all CSS rules with the necessary vendor prefixes for the various existing browsers.

Then we shall use a combination of **prettier**, **eslint** and **stylelint** to format and lint **Javascript** and **CSS** code. As **CI** service, we will have **Semaphore**, to continuously enforce our code styles.

Finally the website can be easily deployed to **Github Pages** using our integrated scripts.

Is this alright to you?
And regarding yesterday's question, have you decided if you want us to use your repository?

**Comment by mgoelzer** [comment]
I think Github pages would be great for this group because folks on the PL side can make edits to copy very easily.

No opinion on the other tools -- you all are the experts, so I trust you.

**Comment by dignifiedquire** [comment]
I suggest using IPFS to deploy the site, rather than using Github pages. Given this is an IPFS event and a static website this seems to be an ideal use case for IPFS.

**Comment by VictorBjelkholm** [comment]
Unless I'm missing some requirements (only read https://github.com/ipfs/conference/issues/23 and linked docs):
- Work without JS (it's a website, not a application)
- Be deployed over IPFS
- Be using Jenkins so we can leverage the auto-deploy for dnslink websites

**Comment by mgoelzer** [comment]
Here's my thought.  We have an urgent need to get the Berlin Developers Meetings pages up and live on the web because the events are only 7 weeks away and we need to run an entire application judging process in that timeframe.  (Question:  is the fact that this repo is now public a sufficient way to meet that requirement?)

However, once we are satisfied that we have met the basic need of application information is publicly available, we should shift to do things right.

> Work without JS (it's a website, not a application)
> Be deployed over IPFS
> Be using Jenkins so we can leverage the auto-deploy for dnslink websites

@VictorBjelkholm Where were/are those requirements documented?  I don't see them in #23 and its doc.  We definitely need to be passing requirements like these @luisptorres ?

**Comment by VictorBjelkholm** [comment]
@mgoelzer it's stack requirements derived from the contents of the linked issue. I don't see any requirements of building a app rather than a website from that document, so just mentioning that as I'm not sure if Gatsby builds websites or apps, but I see a mention of React which usually is used for apps and not websites. Should not be needed at all for the website (unless it's just used for generating the website).

Deployment stuff is just how we usually handle websites to make it as simple and fast as possible. It's literally one line to add CI + deployment, so we should take advantage of that, especially since we're time constrained.

**Comment by mgoelzer** [comment]
I want to uncouple the discussion of IPFS-vs-GHP hosting from the other issues @VictorBjelkholm is raising like a Jenkins deployment flow, so I created #26 to debate the IPFS/HTTPS point specifically.

**Comment by VictorBjelkholm** [comment]
@jfranciscosousa as long as we end up with a directory with static files and relative links everywhere, stuff will work out-of-the-box. See how it works for peerpad for example: https://github.com/ipfs-shipyard/peer-pad/blob/master/ci/Jenkinsfile

**Comment by jfranciscosousa** [comment]
It's perfectly fine then, our build script does that, it saves all optimized static files to a `public` folder (can be any other folder obviously).

**Comment by satazor** [comment]
Just for reference, I've made https://github.com/moxystudio/gatsby-plugin-ipfs. It turns out the Gatsby doesn't support relative paths which is a must for sites to be deployed in IPFS. That plugin gets around it, see https://github.com/moxystudio/gatsby-plugin-ipfs#but-how.
