### ISSUE TITLE
Acceptance/Rejection email text

### ISSUE THREAD

**Issue by mgoelzer** [ipfs/conf#36]
We need to send out acceptance emails soon.  The email needs to point accepted invitees to a next step (to confirm they are coming).  They also need to pay a fee-- perhaps through EventBrite.

Here is a Google doc where we can iterate on the wording of the acceptance emails:  https://docs.google.com/document/d/1Q7ENFtBM9SM4yXa7yXqdF_o2_8SV0_ROfxZoscaPD60/edit#

There are three categories of invitees:

1.  **PL Team/Core** - these folks need to register, but not pay, and be directed to book their own reimburseable flight per the PL travel policy.  They don't need to make accommodations since we'll roll them into the room block.  (@jamiejn, lmk if this sounds right to you.)
1. **Non-PL invitees who ARE NOT requesting financial assistance** - Just need to give them EventBrite/payment form, registration form, dates and recommended hotels.
1. **Non-PL invitees who ARE requesting financial assistance** - This is the most complex category.  First, we have to resolve #31 .  Then we will to customize the email based on whether they are requesting waiver only or waiver+travel assistance.  My suggestion is that for those requesting travel assistance we ask them to book their own flights and submit the receipt to Phil for reimbursement; for accommodations, we can put them in the room block like PL Team/Core.

cc @flyingzumwalt

**Comment by mgoelzer** [comment]
@flyingzumwalt In thinking through this further, I think we need to direct the invitees to a registration form even if we use EventBrite.  First, I'm not sure we'll have an EventBrite account set up by tomorrow; second, not every attendee is paying but we still need them to ACK our acceptance of their application.

Why don't we just direct them to a Google form where they indicate that they are coming and what they're coming for (IPFS or libp2p or both)?  We can say in the email that we will distribute an EventBrite link to pay registration fees next week.

Google form fields:
- Name
- I am attending (checkboxes):
  [ ] IPFS Developers Meeting, 9-11 July
  [ ] libp2p Developers Meeting, 9-11 July
- Email
- Github handle
- Emergency contact name and phone number (<-- might not be a bad idea to have this)

**Comment by mgoelzer** [comment]
I have finalized the [acceptance and rejection emails](https://docs.google.com/document/d/1Q7ENFtBM9SM4yXa7yXqdF_o2_8SV0_ROfxZoscaPD60/edit#).  Note that there is now an entire workflow:  [email] -> [google form] -> [in the future, we'll follow up to collect their payments & provide hotel info]

How we communicate with both the invitees and those we reject will reflect on PL and our community in general, so I'd appreciate any feedback about the tone, the user experience with the form, etc.

Any comments?  @flyingzumwalt @jamiejn @meiqimichelle @diasdavid @whyrusleeping

**Comment by jamiejn** [comment]
@mgoelzer Can we also include a bullet for arrival and departures dates to help keep a total number of rooms needed throughout the week? I know most attendees will make their own room reservations but I want to make sure we have enough reserved in the block.

Will PL Core/Team that are attending get the acceptance email/be asked to fill out the Google form as well? Those are the arrival/departure dates that I definitely need for the hotel block. Otherwise, I will just ask PL Core/Team to add their dates to a spreadsheet.

**Comment by jamiejn** [comment]
I see from the Google doc that PL Core/Team will be asked to complete the registration form so that answers that question. It would be helpful to get their arrival/departure dates when they fill out the form. It can be an optional question for those that are not able to determine their schedule yet.

**Comment by mgoelzer** [comment]
Jamie, reading your comments and I am beginning to think that we should not have PL Team/Core complete the registration form at all.  (Since we are sending them their own email, we can customize the process for them however we want.)  An internal spreadsheet actually seems easier to manage because people's attendance can be nailed down one by one, they can come back a few days from now and update their arrival/departure dates, etc.  It's how you all did the Lisbon events and I thought that went very smoothly.

**Comment by flyingzumwalt** [comment]
We’ve already made them fill out one form (or two forms) to apply to attend. We should only make them fill out one more form in order to register. Any more forms than that is just wasting their time.

The form you’ve created only asks for one new piece of information: an emergency contact number. We already have all of the other information from their initial application. Don’t make them fill out an entire form just to confirm receipt of your email.

We do need to decide how we will handle registrations, how we will accept payments, and what information we need to gather at registration -- tshirt sizes, arrival/departure dates, which hotel they will stay at, whether they have dietary constraints, etc. We should gather all of this information at once when they register. We should not rush through planning this step. That's a recipe for mountains of confusion and lots of last minute emails. Let's discuss that in https://github.com/ipfs/conference/issues/38 rather than forcing it into the comments about confirmation emails.

**Comment by mgoelzer** [comment]
Your reply made me laugh.  I agree the form is stupid.  We're in this situation only because I wanted to avoid writing an acceptance email that says "Please reply to this email to confirm you will attend."  I had that originally, and I just imagined a torrent of replies with each with special circumstances and questions, and the whole process just becoming disorganized and manual.  I wanted to have a more manageable (for our team) call to action, and thus this issue, _ Acceptance/Rejection email text_, turned into an entire workflow.

**Comment by mgoelzer** [comment]
Good point @meiqimichelle .  I closed it without comment.  If someone wants to reopen, they can do that.
