### ISSUE TITLE
Setting the Daily Schedule

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#44]
This is getting more detailed than the information in https://github.com/ipfs/conf/issues/8

We need to tell the venue, A/V team, etc when things will open, close, start, stop, etc. I assembled a draft schedule at [Schedule Planning](https://docs.google.com/spreadsheets/d/1Rxxzp5fKDnaXVZgD0sJxL-ZOQ0S2keCe6Ksg9ZoRYE0/edit?usp=sharing) spreadsheet, but here are the key items:

| What |  When |
|---|---|
| When will the **venue open** each day?  | **8:00** |
| When will the **first session start** each day? | **9:30** |
| When will **lunch start & end**? | **13:00-14:30** |
| When will we **end the final session** each day? | **18:30** |
| When will the **venue close** each day? | **19:00** |

Does everyone agree with these times? Does anyone want to push for starting 30 minutes earlier (9am) and ending 30 minutes earlier (6pm)?

**Comment by flyingzumwalt** [comment]
FYI @LorenzoPilia I think you're right - we shouldn't squeeze lunch into 1 hour. I made it 90 minutes.

**Comment by flyingzumwalt** [comment]
@mgoelzer will you use this same basic schedule for the libp2p meetings?

**Comment by LorenzoPilia** [comment]
@flyingzumwalt  Considering that:

- The first session will only start at 9:30
- Evening activities are planned every day
- All the attendees will be staying in a hotel nearby that provides breakfast

Why don't we open the doors at 9:00? I find it unlikely that people will arrive earlier than that. Of course we (organising team, video team, etc.) can arrive earlier at 8:00, and if someone shows up before 9:00 they can also come in. But I don't think we need to ask the venue and their entire team to be ready at 8:00.

We need to take a decision on the schedule so we can communicate it to the venue asap! Cc @jamiejn

**Comment by jamiejn** [comment]
@LorenzoPilia I agree we should have the venue open and ready for guests by 9:00am and ending at 7:00pm. The venue coordinator will meet the planning team, AV team, etc. earlier to get everything set-up and any guests that arrive early can still come in but I don't think many will arrive more than 30 minutes early. 

I would vote to keep the schedule starting at 9:30am, ending at 6:30pm to give people time to have breakfast at the hotel, make the 15 minute walk over to Haus Ungarn and arrive by 9:00-9:15, get a coffee and get settled before we begin. Also, our evening events are planned to begin at 7:00pm so ending at 6:30pm would work well for people to move to the next venue without losing anyone in the downtime.

**Comment by mgoelzer** [comment]
I have designed the basic structure I propose for libp2p to use here:  https://docs.google.com/spreadsheets/d/1Rxxzp5fKDnaXVZgD0sJxL-ZOQ0S2keCe6Ksg9ZoRYE0/edit#gid=135146130

Seeking feedback.  @flyingzumwalt @diasdavid @meiqimichelle 

Briefly, my reasoning for Thursday is:  put the high value, cognitively complex tasks (protocol design discussions) in the mid-morning, then break for lunch, then have some after lunch presos while people digest their lunch, then dive into one more round of cognitively complex work (poster creations).

For Friday:  the goal is mostly unconference time because people are going to think of topics as the event is going on and they are start getting more excited and having spontaneous ideas.  We'll use the normal propose-and-vote unconference style to ensure that there is a clear definition of the activities that morning.

**Comment by LorenzoPilia** [comment]
@flyingzumwalt @mgoelzer Last week we discussed and agreed to open the doors for the audience at 9am, this is what has been communicated to the venue, please adjust the schedule accordingly. Mike, I see you have a keynote scheduled on Thursday at 9am, can you move it to 9:30?

**Comment by LorenzoPilia** [comment]
@flyingzumwalt If I remember correctly, you mentioned we should do the group picture on Wednesday morning before the unconference begins, and include it in the schedule, so everyone is aware that's happening.

**Comment by mgoelzer** [comment]
@LorenzoPilia Thanks - good catch on the times.  I've fixed it so first activity is not until 9:30.
