### ISSUE TITLE
Make our Sched site publicly accessible

### ISSUE THREAD

**Issue by mgoelzer** [ipfs/conf#45]
I know our [Sched site](https://developersmeetingsberlin2018.sched.com/) is incomplete, but there's enough useful content there now that I'd vote to open it up publicly and share it through the README's in `[ipfs|libp2p]/developers-meeting` repos.  To do so, I need to upgrade the account to a paid "Engage" account ($500).

Anyone object to making the current Sched public?

@flyingzumwalt @meiqimichelle @diasdavid @LorenzoPilia

**Comment by mgoelzer** [comment]
Thanks @LorenzoPilia , I've actually never been on the admin side of a Sched, so this is interesting to see.

Yes, fully public is what I'm thinking.  

My goal is really just to disseminate tentative schedule information.  We could also make the [Google Docs spreadsheet](https://docs.google.com/spreadsheets/d/1Rxxzp5fKDnaXVZgD0sJxL-ZOQ0S2keCe6Ksg9ZoRYE0/edit#gid=135146130) world readable if making Sched public is not appropriate yet.

**Comment by flyingzumwalt** [comment]
Question: If we make it public now, will that make it awkward when we start adding detailed items to the schedule? There will be a period where some sessions are filled in and others aren't. Will that cause confusion? Is it better to make the site public after we've populated it with all the session info? Or should we just build the session list in a spreadsheet and then bulk-import the updates when they're ready?

Otherwise let's go ahead and make it public.

Side note: @LorenzoPilia the [grid view of the schedule](https://developersmeetingsberlin2018.sched.com/grid/) gets odd when we include the evening venues in Sched's list of Venues. I wonder if we should have one "Venue" for evening activities and then put the specific venue details in each evening event.

**Comment by mgoelzer** [comment]
@flyingzumwalt I'm ok with either. Understand the concerns you're raising with sharing it now.

**Comment by flyingzumwalt** [comment]
I think we can just do all the editing in spreadsheets and bulk update when it's ready to ship. Go ahead and make it public.

**Comment by LorenzoPilia** [comment]
The schedule is live and public at https://developersmeetingsberlin2018.sched.com/

I've changed the times so they're consistent with the spreadsheet (might be confusing otherwise).

@flyingzumwalt what do you mean with "the grid view of the schedule gets odd when we include the evening venues"?

**Comment by meiqimichelle** [comment]
@flyingzumwalt was there something that needed to be changed re: the grid layout?

**Comment by flyingzumwalt** [comment]
In the grid view each venue gets a column, so if we list the evening locations as venues that adds three mostly-empty columns to the grid. This makes it harder to read the practical info about which sessions are in which room. Worse - the venue’s columns are in alphabetical order from left to right, so the empty columns are missed together with the breakout rooms.

My solution: don’t list the evening locations as venues in sched. Maybe have an “Evening Activities” venue and put the location info into the time entry for each evening activity.

**Comment by mgoelzer** [comment]
Agree with Matt.  The way it is now, it kind of looks like Bar Babette is the name of a room or area at the venue.

**Comment by LorenzoPilia** [comment]
Evening venues are now listed as "Other venue" so they appear last in grid view.
