### ISSUE TITLE
Define Criteria for Deciding Who Should Attend

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/conf#5]
The Developer Meetings should be  tight, focused working meetings for people who have been actively contributing to our code bases, designs, documentation and roadmaps. In order to achieve that, we must limit the attendees to:
 
- People who are responsible for delivering code, designs, and documentation that directly contributes to achieving our strategic goals
- A small number of key users who have deep knowledge of the technology stack, APIs, specifications and working processes.
- (maybe) 1-5 invited participants to provide perspective, inspiration and guidance from other contexts

People Who Are Automatically Eligible:
- Working Group Captains 
- anyone who has had KRs assigned to them in the past 6 months

Criteria for all other Applicants:
- Quality of session proposal(s)
- Proven familiarity with the APIs, specifications, and working processes of our projects
- Proven commitment to contribute to the evolution of these protocols

Favorable Factors:
- participation on github, especially if you've had github issues assigned to you by any of the Captains and WG members
- participation in the IPFS All Hands Call in the past 12 months
- participation and contributions on discourse

**Comment by mgoelzer** [comment]
@flyingzumwalt The **IPFS Developer Meeting** (fka Summit) criteria you describe in the original issue seem reasonable to me.

For the **libp2p Developer Meeting**, my proposal for acceptance follows the same basic logic.  The goal again is keep this event small (~20 people) and focused, in order to facilitate high-bandwidth discussions between people who are already highly knowledgeable about libp2p.  To that end, I'd like to admit people who fall into one of these categories:
* **Major open source contributors.**  People who are responsible for delivering code, designs, and documentation that directly contributes to achieving our strategic goals.  (words copied from IPFS)
* **Users.** A small number of key users who have deep knowledge of the technology stack, APIs, specifications and working processes. (again, same words as IPFS)
* **Special Invitations.**  We may want to add a few exceptional people who don't fit the criteria above, but would bring some unique value to the discussion.  This category will be used sparingly.
